apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: kube-system
spec:
  containers:  
  - image: hub.bonc:5000/busybox
    command:
     - sleep
     - "36000"
    imagePullPolicy: IfNotPresent
    name: busybox
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
  restartPolicy: Always

