apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: ceph-rbd
provisioner: kubernetes.io/rbd
parameters:
    monitors: 172.16.3.122:6789,172.16.3.123:6789,172.16.3.124:6789
    adminId: admin
    adminSecretName: ceph-secret
    adminSecretNamespace: "kube-system"
    pool: rbd
    userId: admin
    userSecretName: ceph-secret
