apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: ceph-rbd
provisioner: kubernetes.io/rbd
parameters:
    monitors: 10.10.3.17:6789,10.10.3.18:6789,10.10.3.19:6789
    adminId: kube
    adminSecretName: ceph-secret
    adminSecretNamespace: "dipper"
    pool: kube
    userId: kube
    userSecretName: ceph-secret
