apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: ceph-rbd
   namespace: dipper
provisioner: kubernetes.io/rbd
parameters:
    monitors: 10.10.3.17:6789,10.10.3.18:6789,10.10.3.19:6789
    adminId: admin
    adminSecretName: ceph-secret
    adminSecretNamespace: "dipper"
    pool: rbd
    userId: admin
    userSecretName: ceph-secret
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zk-pv1
  namespace: dipper
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  rbd:
    monitors:
      - 10.10.3.17:6789
      - 10.10.3.18:6789
      - 10.10.3.19:6789
    pool: rbd
    image: zk1
    user: admin
    secretRef:
      name: ceph-secret
    fsType: ext4
    readOnly: false
  storageClassName: ceph-rbd
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zk-pv2
  namespace: dipper
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  rbd:
    monitors:
      - 10.10.3.17:6789
      - 10.10.3.18:6789
      - 10.10.3.19:6789
    pool: rbd
    image: zk2
    user: admin
    secretRef:
      name: ceph-secret
    fsType: ext4
    readOnly: false
  storageClassName: ceph-rbd
  persistentVolumeReclaimPolicy: Recycle
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zk-pv3
  namespace: dipper
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  rbd:
    monitors:
      - 10.10.3.17:6789
      - 10.10.3.18:6789
      - 10.10.3.19:6789
    pool: rbd
    image: zk3
    user: admin
    secretRef:
      name: ceph-secret
    fsType: ext4
    readOnly: false
  storageClassName: ceph-rbd
  persistentVolumeReclaimPolicy: Recycle
