kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zk-claim
  namespace: dipper
spec:
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: ceph-rbd
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zk-claim2
  namespace: dipper
spec:
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: ceph-rbd
