---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monitoring-influxdb
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: influxdb
    spec:
      containers:
      - name: influxdb
        #image: gcr.io/google_containers/heapster-influxdb-amd64:v1.1.1
        image: hub.bonc:5000/influxdb:0.6
        #image: hub.bonc:5000/google_containers/heapster-influxdb-amd64:v1.1.1
        volumeMounts:
        - mountPath: /data
          name: influxdb-storage
      volumes:
      - name: influxdb-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    task: monitoring
    # For use as a Cluster add-on (https://github.com/kubernetes/kubernetes/tree/master/cluster/addons)
    # If you are NOT using this as an addon, you should comment out this line.
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: monitoring-influxdb
  name: monitoring-influxdb
  namespace: kube-system
#spec:
#  ports:
#  - port: 8086
#    targetPort: 8086
#  selector:
#    k8s-app: influxdb
spec:
  type: NodePort
  ports:
  - name: http
    port: 8083
    targetPort: 8083
    nodePort: 30021
  - name: api
    port: 8086
    targetPort: 8086
    nodePort: 30022
  selector:
    k8s-app: influxdb
