---
# cluster Service
apiVersion: v1
kind: Service
metadata:
  name: cephkafka2
  namespace: cuijishuo 
spec:
  ports:
  - port: 9092
  selector:
    app: cephkafka2
---
# cluster DNS
apiVersion: v1
kind: Service
metadata:
  name: cephbroker2
  namespace: cuijishuo
  labels:
    app: cephbroker2
spec:
  ports:
  - port: 9092
  # [podname].broker.kafka.svc.cluster.local
  clusterIP: None
  selector:
    app: cephkafka2
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: cephkafka2
  namespace: cuijishuo
spec:
  serviceName: "cephbroker2"
  replicas: 3
  template:
    metadata:
      labels:
        app: cephkafka2
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - cephbroker2
              topologyKey: "kubernetes.io/hostname"
      terminationGracePeriodSeconds: 10
      containers:
      - name: cephbroker2
        #image: solsson/kafka-persistent:0.10.1
        #image: dipperroy/kafka:0.10.2.1-alpine
        image: hub.bonc:5000/kafka:0.10.2.1-alpine
        ports:
        - containerPort: 9092
        resources:
          limits:
            cpu: "1"
            memory: 20Gi
          requests:
            cpu: "1"
            memory: 2Gi
        command:
        - sh
        - -c
        - " ./bin/kafka-server-start.sh config/server.properties --override broker.id=1$(hostname | awk -F'-' '{print $2}') --override delete.topic.enable=true --override zookeeper.connect=zk.cuijishuo:2181"
        env:
        - name: KAFKA_HEAP_OPTS
          value: "-Xmx2G -Xms2G"
        volumeMounts:
        - name: cephkafkadir2
          mountPath: /opt/kafka/data
  volumeClaimTemplates:
  - metadata:
      name: cephkafkadir2
      namespace: cuijishuo
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
      storageClassName: cuijishuo
