apiVersion: v1
kind: ReplicationController
metadata:
  name: alpine
  namespace: testbonc
  labels:
    name: alpine
spec:
  replicas: 1
  selector:
    name: alpine
  template:
    metadata:
      labels:
        name: alpine
    spec:
      containers:
        - image: alpine:3.5
          imagePullPolicy: Always
          name: alpine
          command: 
            - "sh" 
            - "-c"
            - "while true;do echo test;done"
          ports:
            - containerPort: 8080
              name: alpine
          volumeMounts:
          - mountPath: /cache
            name: cache-volume
      volumes:
      - name: cache-volume
        emptyDir: {}
