apiVersion: v1
kind: Service
metadata:
  name: redis-nodes
  namespace: dipper
  labels:
    service: redis
spec:
  clusterIP: None
  ports:
    - port: 6379
      name: redis
  selector:
    name: redis-node
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: dipper
  labels:
    service: redis
spec:
  ports:
    - port: 6379
      name: redis
  selector:
    name: redis-node
    role: master
---
apiVersion: v1
kind: Service
metadata:
  name: redis-readonly
  namespace: dipper
  labels:
    service: redis
spec:
  ports:
    - port: 6379
      name: redis
  selector:
    name: redis-node
    role: slave
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-sentinel
  namespace: dipper
data:
  node.conf: |
    protected-mode no
    port 6379
    tcp-backlog 511
    loglevel notice
    logfile ""
    dir /redisms
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis
  namespace: dipper
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  serviceName: redis-nodes
  replicas: 3
  template:
    metadata:
      labels:
        name: redis-node
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        # Redis
        - name: redis-node
          image: redis:3.2
          command:
            - redis-server
          args:
            - /config/node.conf
          ports:
            - name: redis
              containerPort: 6379
          volumeMounts:
            - name: data
              mountPath: /redisms
            - name: redis-config
              mountPath: /config
          resources:
          livenessProbe: &healthcheck
            exec:
              command: [ "redis-cli", "ping" ]
          readinessProbe:
            <<: *healthcheck

        # Sentinel
        - name: redis-sentinel
          image: redis:3.2
          command: [ "bash", "-c", "touch sentinel.conf && redis-sentinel sentinel.conf" ]
          ports:
            - name: sentinel
              containerPort: 26379
          resources:
          livenessProbe: &healthcheck
            exec:
              command: [ "redis-cli", "-p", "26379", "ping" ]
          readinessProbe:
            <<: *healthcheck

        # Sidecar
        - name: redis-sidecar
          image: commercialtribe/redis-sentinel-sidecar:v20170425.0
          imagePullPolicy: Always
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: pod-info
              mountPath: /etc/pod-info
          readinessProbe:
            exec:
              command: [ "cat", "booted" ]
          resources:

      volumes:
        - name: pod-info
          downwardAPI:
            items:
              - path: labels
                fieldRef:
                  fieldPath: metadata.labels
        - name: redis-config
          configMap:
            name: redis-sentinel
  volumeClaimTemplates:
    - metadata:
        name: redisms 
        namespace: dipper
      spec:
        accessModes: 
          - ReadWriteOnce
          - ReadWriteMany
        resources:
          requests:
            storage: 5Gi
        storageClassName: ceph-rbd
